# Generated by Django 5.1.1 on 2024-12-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Hobbies',
            field=models.ManyToManyField(blank=True, to='api.hobby'),
        ),
    ]
