# Generated by Django 5.1.1 on 2024-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='DOB',
        ),
        migrations.AddField(
            model_name='user',
            name='Hobbies',
            field=models.ManyToManyField(to='api.hobby'),
        ),
        migrations.DeleteModel(
            name='UserHobby',
        ),
    ]
